# Generated by Django 4.1.4 on 2023-01-02 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="YearsGraph",
            fields=[
                (
                    "stat",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="media/images/")),
            ],
        ),
        migrations.CreateModel(
            name="YearsStats",
            fields=[
                (
                    "stat",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("year", models.IntegerField()),
                ("salary", models.IntegerField()),
                ("prof_salary", models.IntegerField()),
                ("count", models.IntegerField()),
                ("prof_count", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Stats",
            fields=[
                (
                    "stat",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                (
                    "graph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prof_stats.yearsgraph",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prof_stats.yearsstats",
                    ),
                ),
            ],
        ),
    ]
