# Generated by Django 4.1.4 on 2023-01-02 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("prof_stats", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="YearsStat",
            fields=[
                (
                    "name",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                (
                    "YearsGraph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prof_stats.yearsgraph",
                    ),
                ),
            ],
        ),
        migrations.RenameModel(
            old_name="YearsStats",
            new_name="YearsTable",
        ),
        migrations.DeleteModel(
            name="Stats",
        ),
        migrations.AddField(
            model_name="yearsstat",
            name="YearsTable",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="prof_stats.yearstable"
            ),
        ),
    ]
