# Generated by Django 4.1.4 on 2023-01-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "prof_stats",
            "0002_yearsstat_rename_yearsstats_yearstable_delete_stats_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="yearstable",
            name="stat",
        ),
        migrations.AlterField(
            model_name="yearstable",
            name="year",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name="YearsStat",
        ),
    ]
