# Generated by Django 4.1.4 on 2023-01-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prof_stats", "0003_remove_yearstable_stat_alter_yearstable_year_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CitiesPercentTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=30)),
                ("percent", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="CitiesSalaryTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=30)),
                ("salary", models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name="YearsGraph",
            new_name="Graph",
        ),
    ]
