# Generated by Django 4.1.4 on 2023-01-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prof_stats", "0006_skillsgraph_skillstable"),
    ]

    operations = [
        migrations.CreateModel(
            name="LatestVacancies",
            fields=[
                (
                    "name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("description", models.TextField()),
                ("skills", models.TextField()),
                ("company", models.CharField(max_length=100)),
                ("salary", models.IntegerField()),
                ("area_name", models.CharField(max_length=100)),
                ("published_at", models.DateTimeField()),
            ],
        ),
    ]
