# Generated by Django 4.1.4 on 2023-01-02 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prof_stats", "0007_latestvacancies"),
    ]

    operations = [
        migrations.AddField(
            model_name="latestvacancies",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=None,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="latestvacancies",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
