# Generated by Django 4.1.4 on 2023-01-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prof_stats", "0008_latestvacancies_id_alter_latestvacancies_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="latestvacancies",
            name="url",
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
